CI: test Python 3.13 and development version of Python 3.14
- add released version Python 3.13
- add development version Python 3.14
- drop EOL version Python 3.8
- use Python 3.13 for all other CI task (i.e., documentation, codestyle,
  etcetera)

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -14,7 +14,7 @@ stages:
       steps:
         - task: UsePythonVersion@0
           inputs:
-            versionSpec: '3.12'
+            versionSpec: '3.13'
         - script: |
             python -m pip install --upgrade build pip setuptools wheel
           displayName: 'Install Python build tools and dependencies'
@@ -43,7 +43,7 @@ stages:
       steps:
         - task: UsePythonVersion@0
           inputs:
-            versionSpec: '3.12'
+            versionSpec: '3.13'
         - script: |
             python -m pip install --upgrade build pip setuptools wheel
           displayName: 'Install Python build tools'
@@ -67,8 +67,8 @@ stages:
         vmImage: 'ubuntu-latest'
       strategy:
         matrix:
-          Python38:
-            python.version: '3.8'
+          Python39:
+            python.version: '3.9'
 
       steps:
         - task: UsePythonVersion@0
@@ -117,8 +117,6 @@ stages:
         vmImage: 'ubuntu-latest'
       strategy:
         matrix:
-          Python38:
-            python.version: '3.8'
           Python39:
             python.version: '3.9'
           Python310:
@@ -127,6 +125,8 @@ stages:
             python.version: '3.11'
           Python312:
             python.version: '3.12'
+          Python313:
+            python.version: '3.13'
 
       steps:
         - task: UsePythonVersion@0
@@ -174,8 +174,8 @@ stages:
         vmImage: 'windows-latest'
       strategy:
         matrix:
-          Python312:
-            python.version: '3.12'
+          Python313:
+            python.version: '3.13'
 
       steps:
         - task: UsePythonVersion@0
@@ -209,8 +209,8 @@ stages:
         vmImage: 'macos-latest'
       strategy:
         matrix:
-          Python312:
-            python.version: '3.12'
+          Python313:
+            python.version: '3.13'
 
       steps:
         - task: UsePythonVersion@0
@@ -236,13 +236,13 @@ stages:
   dependsOn: check_codestyle
   condition: succeededOrFailed()
   jobs:
-    - job: Python313_dev
+    - job: Python314_dev
       pool:
         vmImage: 'ubuntu-latest'
       steps:
         - script: |
             sudo add-apt-repository ppa:deadsnakes/nightly
-            sudo apt-get update && sudo apt-get install -y --no-install-recommends python3.13-dev python3.13-venv
+            sudo apt-get update && sudo apt-get install -y --no-install-recommends python3.14-dev python3.14-venv
           displayName: Install Python development version from the deadsnakes PPA
         - script: |
             sudo apt-get update && sudo apt-get install -yq --no-install-suggests --no-install-recommends \
@@ -251,8 +251,8 @@ stages:
           displayName: 'Install dependencies'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
-            python3.13 -m ensurepip --upgrade
-            pip3.13 install -U build pip setuptools wheel pybind11 cython || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m ensurepip --upgrade
+            pip3.14 install -U build pip setuptools wheel pybind11 cython || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install build, pip, setuptools, wheel, pybind11, and cython'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
@@ -260,12 +260,12 @@ stages:
             wget https://github.com/numpy/numpy/releases/download/v${numpy_version}/numpy-${numpy_version}.tar.gz
             tar xzvf numpy-${numpy_version}.tar.gz
             cd numpy-${numpy_version}
-            python3.13 -m build || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
-            python3.13 -m pip install . --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m build || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m pip install . --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install latest available version of NumPy'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
-            pip3.13 install -U pythran || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            pip3.14 install -U pythran || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install pythran'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
@@ -273,25 +273,25 @@ stages:
             wget https://github.com/scipy/scipy/releases/download/v${scipy_version}/scipy-${scipy_version}.tar.gz
             tar xzvf scipy-${scipy_version}.tar.gz
             cd scipy-${scipy_version}
-            python3.13 -m build || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
-            python3.13 -m pip install . --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m build || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m pip install . --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install latest available version of SciPy'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
             # remove numdifftools for now as it pulls in statsmodels, that wants to build with NumPy 1.14.5
-            pip3.13 install asteval uncertainties dill emcee flaky pytest pytest-cov || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            pip3.14 install asteval uncertainties dill emcee flaky pytest pytest-cov || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install latest available version of Python dependencies'
         - script: |
-            python3.13 -m build
-            python3.13 -m pip install '.[test]' --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            python3.14 -m build
+            python3.14 -m pip install '.[test]' --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Build wheel/sdist and install lmfit'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
-            pip3.13 list || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
+            pip3.14 list || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'List installed Python packages'
         - script: |
             export PATH=/home/vsts/.local/bin:$PATH
-            pip3.13 install pytest-azurepipelines
+            pip3.14 install pytest-azurepipelines
             cd $(Agent.BuildDirectory)/s/tests
             pytest || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Run test-suite'
