CI: hack to allow_failure for Python development version

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -136,17 +136,18 @@ stages:
             export PATH=/home/vsts/.local/bin:$PATH
             curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
             python3.10 get-pip.py --user
-            pip3.10 install -r requirements-dev.txt -U --user
+            pip3.10 install -r requirements-dev.txt -U --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install latest available versions of Python dependencies'
         - script: |
-            python3.10 setup.py install --user
+            python3.10 setup.py install --user || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Install lmfit'
         - script: |
+            export PATH=/home/vsts/.local/bin:$PATH
             pip3.10 list
           displayName: 'List installed Python packages'
         - script: |
             pip3.10 install pytest-azurepipelines --user
-            pytest
+            pytest || echo -e "\043#vso[task.logissue type=warning;] Allowed failure for development version!!"
           displayName: 'Run test-suite'
 
 - stage: build_documentation
